### PR TITLE
Adding BibTeX support.

### PR DESCRIPTION
**Pull request by mzhaox**
A possible solution to issue #7. The solution is described in the comments, but I can paste it here for convenience.

1. copy .bib files to the output directory
2. cd into output directory
3. call bibtex on the jobname (preview) aux file
4. call LaTeX compiler twice

### CODE REVIEW

**Comment by ajshort** [comment]
I'm a little hesitant to begin adding complex build support, and would probably prefer to instead fix latexmk support. Are you also on Windows and running into the same error using latexmk?

**Comment by mzhaox** [comment]
I just tried using latexmk, setting "latex-preview.command" to "latexmk". I get a red box in the top right of the preview window saying "error compiling preview".

**Comment by ajshort** [comment]
Could you please click on the "error compiling preview" popup, and copy any error output into the issue and I will have a look. Also, what platform are you on?

**Comment by mzhaox** [comment]
I am on Windows 10. However, it looks like the error was due to me not having Perl installed. Everything works once I install Perl. I can also make this remark on issue #7 also, if that is helpful.

**Comment by ajshort** [comment]
I will have a look into adding some sort of pop-up saying to install perl, as this is an issue a few people have run into. I've opened this as #10.

**Pull request closed without merging**
